l1 = 0.0
l2 = 0.0
scale = 0.4
num_layers = 3
layer_size = 110
activation = "tanh"
max_iter = 300

directory = "./test_bench/hartmann6/"
main_funct = "hartmann"
constr = []
bounds = [[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]
