l1                   = 0.0
l2                   = 0.0
scale                = 0.4
max_iter             = 200
activation           = "relu"
num_layers           = 3
layer_size           = 50
directory            = "./test_bench/enb/"
