l1 = 0.0
l2 = 0.0
scale = 0.4
num_layers = 3
layer_size = 20
activation = "tanh"
max_iter = 300

constrain_l1 = 0.0
constrain_l2 = 0.0
constrain_scale = 0.4
constrain_num_layers = 2
constrain_layer_size = 20
constrain_activation = "tanh"
constrain_max_iter = 20

directory = "./test_bench/optCase/"
main_funct = "main_function"
constr = ['constrain1']
bounds = [[-5,5],[-3,3],[-2.5,2.5]]
