l1 = [0]
l2 = [0]
scale = [0.4]
num_layers = [2]
layer_size = [20]
activation = ["tanh"]
max_iter = [100]
dim = 6
outdim = 1
num_train = 60
num_test = 2
funct = "hartmann6"
bounds = [[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]
